# Generated by Django 6.0.3 on 2026-04-13 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_alter_lesson_options_question_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('course_group', 'Course Group')], default='course_group', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.OneToOneField(help_text='The course this chat room belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='courses.course')),
                ('participants', models.ManyToManyField(blank=True, help_text='Users who can access this chat room.', related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectMessageRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(help_text='Course context for this DM.', on_delete=django.db.models.deletion.CASCADE, related_name='dm_rooms', to='courses.course')),
                ('participants', models.ManyToManyField(help_text='The two users in this DM conversation.', related_name='dm_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, help_text='Optional file attachment.', null=True, upload_to='chat_attachments/%Y/%m/')),
                ('attachment_name', models.CharField(blank=True, default='', help_text='Original filename of the attachment.', max_length=255)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('system', 'System')], default='text', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dm_room', models.ForeignKey(blank=True, help_text='Direct message room (null if this is a group message).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.directmessageroom')),
                ('room', models.ForeignKey(blank=True, help_text='Course group chat room (null if this is a DM).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['room', 'created_at'], name='chat_messag_room_id_5feac5_idx'), models.Index(fields=['dm_room', 'created_at'], name='chat_messag_dm_room_508327_idx')],
            },
        ),
    ]
