# Generated by Django 6.0.3 on 2026-06-08 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='course',
            field=models.OneToOneField(help_text='The course this chat room belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='courses.course'),
        ),
    ]
