# Generated by Django 6.0.3 on 2026-06-08 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this chat room.', related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directmessageroom',
            name='course',
            field=models.ForeignKey(help_text='Course context for this DM.', on_delete=django.db.models.deletion.CASCADE, related_name='dm_rooms', to='courses.course'),
        ),
        migrations.AddField(
            model_name='directmessageroom',
            name='participants',
            field=models.ManyToManyField(help_text='The two users in this DM conversation.', related_name='dm_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='dm_room',
            field=models.ForeignKey(blank=True, help_text='Direct message room (null if this is a group message).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.directmessageroom'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Course group chat room (null if this is a DM).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'created_at'], name='chat_messag_room_id_5feac5_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['dm_room', 'created_at'], name='chat_messag_dm_room_508327_idx'),
        ),
    ]
