# Generated by Django 6.0.3 on 2026-06-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System'), ('enrollment', 'Enrollment'), ('course_update', 'Course Update'), ('achievement', 'Achievement'), ('mentor_reply', 'Mentor Reply'), ('deadline', 'Deadline'), ('certificate', 'Certificate'), ('chat_message', 'Chat Message')], max_length=20),
        ),
    ]
