# Generated by Django 6.0.3 on 2026-04-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_populate_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
    ]
