# Generated by Django 6.0.3 on 2026-04-04 13:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='size',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
